### ISSUE TITLE
4.1.0 has published without dist directory

### ISSUE THREAD

**Issue by pathikdevani** [arthurbergmz/webpack-pwa-manifest#110]
I have just confirmed using `npm pack webpack-pwa-manifest@4.1.0`.

```
Error: Cannot find module './dist/index.js'
Require stack:
- /app/available_modules/1571072478000/webpack-pwa-manifest/index.js
- /app/index.js
at Module._resolveFilename in core  — line 780
at Module._load in core  — line 685
at Module.require in core  — line 838
at Module.require in core  — line 2418
at require in core  — line 74
 in core  — line 1
```

https://npm.runkit.com/webpack-pwa-manifest

**Comment by pathikdevani** [comment]
As of now, I reverted back and strictly depend on version `4.0.0`.

like `"webpack-pwa-manifest": "4.0.0"`.

**Comment by arthurbergmz** [comment]
I'm really really sorry about this, it has not been easy to find some time to look after this project.
Updated.

Cheers,
Arthur.

**Comment by pathikdevani** [comment]
@arthurbergmz Thanks for quick support. I will look into `4.1.1`.

**Comment by sirjuan** [comment]
Thank you, now this works fine with Create React App!
