### ISSUE TITLE
Latest version requires html-webpack-plugin

### ISSUE THREAD

**Issue by greggb** [arthurbergmz/webpack-pwa-manifest#111]
After upgrading `4.0.0` to `4.1.1` running a build throws the following error

```
[1]
[1] Error: Cannot find module 'html-webpack-plugin'
[1] Require stack:
[1] - node_modules/webpack-pwa-manifest/dist/generators/tapable.js
[1] - node_modules/webpack-pwa-manifest/dist/index.js
[1] - node_modules/webpack-pwa-manifest/index.js
```

Which seems related to the changes in #101.

I don't use `html-webpack-plugin` for my project, so it's not available as a dependency. Does this need to be listed as a `dependency` or `peerDependency` now?

**Comment by thasmo** [comment]
@arthurbergmz this effectively breaks my webpack build (node 10, npm 6.12) - this should be fixes asap imo.

**Comment by thasmo** [comment]
@JeandeCampredon, any idea why this is?

**Comment by JeandeCampredon** [comment]
My bad.
Catching was necessary : 
https://github.com/arthurbergmz/webpack-pwa-manifest/pull/113

I haven't looked much further though I think this is what you need for now.
I guess we should find a way to run tests on an independent environnement .

**Comment by greggb** [comment]
Thanks @JeandeCampredon. Verified a successful build with that change, so should remove the blocking issue once released.

**Comment by MatTheCat** [comment]
Just stumbled upon this issue. Will #113 get merged?
