### ISSUE TITLE
iOS Web Application Configuration

### ISSUE THREAD

**Issue by sim642** [arthurbergmz/webpack-pwa-manifest#13]
[iOS uses special `<meta>` tags for Web Application Configuration](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) as opposed to the Web App Manifest. The functionality of both overlaps a lot so I think it makes sense if this plugin could optionally also inject iOS-specific Web App Configuration `<meta>` tags as the information is already being put into `manifest.json`. Having a separate plugin for just that sounds excessive. It would make this plugin much better suited for production use where iOS devices also need to be supported.

A new plugin option, e.g. `ios` could be added for this. A `false` value (possibly by default to keep existing behavior) would disable the injection of these `<meta>` tags. A `true` value would enable this injection. An object might also be sensible to support as the value to specify iOS only configuration (launch screen image, whether to inject icons normally or precomposed, etc).

**Comment by arthurbergmz** [comment]
Upcoming feature

**Comment by arthurbergmz** [comment]
In development.
It will be release with **v3.2.0**.

**Comment by arthurbergmz** [comment]
Please, update to **v3.2.0**.
