### ISSUE TITLE
Output name interpolation

### ISSUE THREAD

**Issue by sim642** [arthurbergmz/webpack-pwa-manifest#19]
Webpack along with many loaders and plugins allow specifying output filenames in interpolated formats such as `[name].[ext]` and`[name].[hash].[ext]`, which are also used for configuration between development and production to toggle what this plugin has "fingerprint" option for.

Currently the naming of output icons is quite hardcoded:
https://github.com/arthurbergmz/webpack-pwa-manifest/blob/383c65999fcfeb5e66321b294670d92c25ce5687/src/Icons.js#L33-L35

It would be great to have support for customizing the filename format using Webpack "standardized" interpolated names, allowing the default format to be something like `icon_[size]x[size].[ext]` or `icon_[size]x[size].[hash].[ext]`. Note the custom `[size]` parameter. Specifying a custom name format would probably have to override the default and also "fingerprint" option.

A similar but separate interpolated format could probably exist for naming the `manifest.json` file, although it would not be as necessary as being able to name the icons.

[loader-utils#interpolateName()](https://github.com/webpack/loader-utils#interpolatename) is what seems to be able to do the necessary translations.

**Comment by arthurbergmz** [comment]
Proposed at #34 . It will be developed for the next release.
Closed.
