### ISSUE TITLE
Custom publicPath option

### ISSUE THREAD

**Issue by kenrick95** [arthurbergmz/webpack-pwa-manifest#20]
As I understand, this plugin right now only reads from webpack output `publicPath`.

One use case for this is that site assets are served at CDN but would like to serve manifest.json under own site (i.e. non-CDN). At current configuration, where manifest.json is served at CDN (which has different origin from own site's origin), Chrome will throw this warning: `Manifest: property 'start_url' ignored, should be same origin as document.` at console.

I realized that there is no way to specify custom `publicPath` yet for this plugin and would like to have that option.

Thanks

**Comment by arthurbergmz** [comment]
Please, update to **v3.3.0**.
Thank you!
