### ISSUE TITLE
is it necessary to preserve IOS icon in the manifest.json?

### ISSUE THREAD

**Issue by bornkiller** [arthurbergmz/webpack-pwa-manifest#21]
This is a question.

I try to use different icon for ios and android like below: 

```javascript
{
  ios: true,
  icons: [
    {
      src: path.resolve('public/android-icon.png'),
      sizes: [144, 196, 256, 512],
      destination: 'android'
    },
    {
      src: path.resolve('public/ios-icon.png'),
      sizes: [144, 196, 256, 512],
      ios: true,
      destination: 'ios'
    }
  ]
}
```

The plugin works well, insert `app-touch-icon` into html, while still preserve related icon in the `manifest.json`, I wonder that, if this will cause browser pick the wrong icon? or, use different icon is just bad idea?

**Comment by arthurbergmz** [comment]
Unfortunatelly, I don't have an Apple device to test it... No one's complaining about it yet, so I think everything's fine.

Can someone test it, please?

**Comment by kenrick95** [comment]
I think right now on iOS Safari, the entries at `manifest.json` will simply be ignored as iOS Safari does not support it yet: http://caniuse.com/#feat=web-app-manifest
