### ISSUE TITLE
publicPath output files

### ISSUE THREAD

**Issue by paulobmarcos** [arthurbergmz/webpack-pwa-manifest#28]
Hey! First of all, thanks for your work!

I found something that could be a bit better. When using the `publicPath` option, the manifest file won't be generated in the specified path. 

The manifest is always being generated at the root of the output path defined in the webpack config.

To fix this issue we would pass, as arguments, both the publicPath and the webpack output path to some functions that need it, instead of just "ignoring" the publicPath if it's not defined like we are doing here: https://github.com/arthurbergmz/webpack-pwa-manifest/blob/63b40dd932cddacf4ef13e5f41f3e2549a931285/src/WebpackPwaManifest.js#L32

We would replace this to something like:
 ```js  
buildResources(_this, _this.options.publicPath, compilation.options.output.publicPath, () => {
 ```
And with this we can make some logic around the publicPath option.

Right now, without any changes, the `output` of the manifest is only its name and its fingerprint. In this case it will always be generated in the webpack output path:
https://github.com/arthurbergmz/webpack-pwa-manifest/blob/63b40dd932cddacf4ef13e5f41f3e2549a931285/src/Injector.js#L41-L44

The idea would be to add the publicPath if it's provided by the user:
```js
const outputSource = joinURI(publicPath || outputPath, output);
callback(null, {
    output: publicPath ? outputSource : output,
    file: outputSource,
...
```

---  ---

We also should address the icons. The icons `destination` property always starts at the same folder level as the manifest file right?

Having this in mind we can do the same thing as above. Instead of:
https://github.com/arthurbergmz/webpack-pwa-manifest/blob/63b40dd932cddacf4ef13e5f41f3e2549a931285/src/Icons.js#L35-L45

We could: 
```js
 const output = icon.destination ? joinURI(icon.destination, filename) : filename;
 const outputSource = (publicPath || outputPath, output); 
 icons.push({ 
   src: output,
   sizes: sizeFormat,
   type 
 }) 
 assets.push({ 
   output: publicPath ? outputSource : output,
   source: buffer, 
   size: buffer.length, 
```

---  ---

So... With this changes this is what would happen:

**Case 1.**
We define a `publicPath`: `publicPath: 'my/path'`.
We define an icon (192x192) with a pre-defined `destination`: 
```
{ ...,
  destination: 'favicons'
}
```
We also define an icon (512x512) without a `destination`.

We would get an output like: 

publicDir
│
└─── my
│         │
│         └─── path
│         │         │  
│         │         │  manifest.json
│         │         │  icon_512x512.png
│         │         └─── favicons
│         │         │          │   
│         │         │          │  icon_192x192.png

 
**Case 2.**
We don't define a `publicPath` and expect the plugin to use the already defined output config of webpack. 

We define an icon (192x192) with a pre-defined `destination`: 
```
{ ...,
  destination: 'favicons'
}
```
We also define an icon (512x512) without a `destination`.

We would get an output like: 

publicDir
│
│manifest.json
│icon_512x512.png
└─── favicons
│         │  icon_192x192.png

---  ---

What do you think of this? Am I missing something? 
If you think this might be a solution I would try to help and make a MR.

Thanks once again!

**Comment by arthurbergmz** [comment]
It's a good suggestion, but the problem might be backwards compatibility. It completely changes the behavior of publicPath.

We could check, for example, if the first character is a dot. If true, then we could join `publicPath` to webpack's `publicPath`.

What do you think?
