### ISSUE TITLE
Manifest: property 'sizes' ignored

### ISSUE THREAD

**Issue by andreasonny83** [arthurbergmz/webpack-pwa-manifest#3]
`Manifest: property 'sizes' ignored, type string expected.`

Looks like Chrome doesn't like the `sizes` array. Maybe something to investigate according to the official documentation. 

![](http://i.imgur.com/kMacgJ9.jpg?2)

**Comment by arthurbergmz** [comment]
Oops, my bad. I didn't notice that one of the pull requests changed it.

Working on it right now.

**Comment by arthurbergmz** [comment]
Let me now if it is working now.

I'll do some refactoring as soon as possible! :)

**Comment by andreasonny83** [comment]
Is the fix included in the version 2.1.6? I can see a commit after that version that doesn't point to any specific version. I will try the latest available shortly anyway and let you know if any problem.
Thanks for your support

**Comment by andreasonny83** [comment]
I confirm version 2.1.6 works fine in my app.
Thanks again @arthurbergmz
