### ISSUE TITLE
Recursive output folder creation with 3.3.4 release

### ISSUE THREAD

**Issue by Guymestef** [arthurbergmz/webpack-pwa-manifest#30]
Hello,

With following version of packages:
    "webpack": "~3.10.0",
    "webpack-hot-middleware": "~2.21.0",
    "webpack-pwa-manifest": "~3.3.4"

Each time the HMR rebuild sources, a new output folder with a manifest file is created inside the normal output folder, ending up after few rebuild with something like that:

/dist/[compiled sources]
/dist/manifest.json
/dist/dist/manifest.json
/dist/dist/manifest.json
/dist/dist/dist/manifest.json
/dist/dist/dist/dist/manifest.json
/dist/dist/dist/dist/dist/manifest.json
...

Everything was fine with "webpack-pwa-manifest": "~3.3.2"

Webpack has the conf output.publicPath set to '/dist/' and output.path set to path.join(__dirname, './ClientApp/dist')

**Comment by arthurbergmz** [comment]
@Guymestef Can you show your Webpack config's plugins array, please?

**Comment by Guymestef** [comment]
Sorry, I can't right now. It's from a work project and I'm off for the rest of the year... ^_^'
I don't know if it will help but the base of the project is from the react-redux template of vs2017 for aspnet core.

**Comment by arthurbergmz** [comment]
@Guymestef I need to see the WebpackPwaManifest config. Did you use the property `filename` in it?

**Comment by Guymestef** [comment]
It's from memory, but I think I used: filename: "manifest.json"

**Comment by arthurbergmz** [comment]
@Guymestef 

Please, update to **v3.4.0** and add `includeDirectory: false` to your WebpackPwaManifest config.

Reopen this issue if it doesn't work yet.
Thank you!
