### ISSUE TITLE
Generating browserconfig.xml and MS tiles

### ISSUE THREAD

**Issue by ciampo** [arthurbergmz/webpack-pwa-manifest#37]
It would be good if this plugin could generate, alongside the webmanifest file, the `browserconfig.xml` needed by Microsoft browsers (and the related tile icons)

**Comment by arthurbergmz** [comment]
browserconfig.xml support will be added to the next version. We will keep discussion under #44 . Closed.

**Comment by panditsavitags** [comment]
is the browserconfig.xml support added?
