### ISSUE TITLE
Choosing which icons are linked in the webmanifest

### ISSUE THREAD

**Issue by ciampo** [arthurbergmz/webpack-pwa-manifest#38]
It would be good if the configuration allowed the user to specify if a group of icons should be included in the manifest file.

Example:

```json
"icons": [
  {
    "src": "src/images/favicon.png",
    "sizes": [48, 144, 512],
    "manifest": true
  },
  {
    "src": "src/images/favicon.png",
    "sizes": [180],
    "ios": true,
    "manifest": false
  } 
]
```

**Comment by arthurbergmz** [comment]
Why a group of icons should not be in the manifest?

**Comment by frlinw** [comment]
@ciampo my second proposition should solve this, check it https://github.com/arthurbergmz/webpack-pwa-manifest/issues/44

**Comment by ciampo** [comment]
@arthurbergmz If we start generating icons for multiple browsers and OSs (e.g Chome, Apple touch icons, safari mask-image, Edge tiles), the Web App Manifest file would very quickly bloat.

Also, some of these icons would be created for specific use cases (e.g the iOS icon with rounded borders, the MS tile icon with a solid color in the background, the chrome icon with a transparent background...).

Putting all the icons in the Web App Manifest would leave the choice of the icon to the browser, given the icon `size` and `type`, which means that potentially Chrome could pick up and use the icon that was made for Edge tiles if that icon has the better combination of image type and resolution.

**Comment by ciampo** [comment]
@frlinw Thanks for putting together that issue — @arthurbergmz it can probably make more sense to discuss all the improvements that we would like to land in the next version in the same issue perhaps?

In that case, we can close this issue (and the other ones that I opened recently) and discuss everything in the same issue

**Comment by arthurbergmz** [comment]
We will keep the discussion under the proposal of #44 . Closed.
