### ISSUE TITLE
Generating safari SVG mask-icon

### ISSUE THREAD

**Issue by ciampo** [arthurbergmz/webpack-pwa-manifest#40]
It would be good if this plugin could generate an SVG icon following the specs of [Safari's mask icon](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html)

(as an example, [Real Favicon Generator](https://realfavicongenerator.net/) does it quite well)

Thanks!

**Comment by acostalima** [comment]
I guess SVG icons are not yet supported then, right?
I'm getting the following error when I add a SVG to icon `src`: 

> Error: It was not possible to read <SVG_FILE_PATH>
