### ISSUE TITLE
Is there a way to inject links to generated images?

### ISSUE THREAD

**Issue by Manidos** [arthurbergmz/webpack-pwa-manifest#41]
Hey!
My problem is that I have many images of different sizes in my `dist` folder, but they are not injected into `index.html`. The images are recognized by the browser (I can see the icons in devtools) `devtools -> application -> manifest`, but favicon on browser tab is empty. Is it a bug or a feature or am I missing something?

![1](https://user-images.githubusercontent.com/16019131/35468720-c93d4e4e-0356-11e8-991a-9c7c10beec75.png)

**Comment by frlinw** [comment]
favicon is not related to the webapp manifest. But it would be nice if webpack-pwa-manifest could manage it as an option
for now, you can check : https://github.com/jantimon/favicons-webpack-plugin

**Comment by arthurbergmz** [comment]
I'll take this as an enchancement, but it's not a priority now.
