### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by frlinw** [arthurbergmz/webpack-pwa-manifest#43]
Webpack 4 is currently in beta (should be released in Feb 2018) and introduce a new plugin system (called tap).

**Comment by arthurbergmz** [comment]
I'll take a look at this as soon as possible!

**Comment by frlinw** [comment]
it can help : https://github.com/GoogleChrome/workbox/issues/1151

**Comment by arthurbergmz** [comment]
Implemented for **v4.0.0**.
