### ISSUE TITLE
Custom properties in manifest like gcm_sender_id

### ISSUE THREAD

**Issue by adelura** [arthurbergmz/webpack-pwa-manifest#46]
Hi, thank you for the plugin!

I was wondering if it's possible to set a custom property in manifest.json? What I'm trying to achieve is to have this field:

``` json
{
  "gcm_sender_id": "547903344792"
}
```

According to [web push book](https://web-push-book.gauntface.com/chapter-06/01-non-standards-browsers/#adding-a-web-app-manifest) it's required to setup Google Cloud Messaging.

**Comment by adelura** [comment]
Okay I just realised that I could do this easily by:

``` js
new WebpackPwaManifest({
      name: 'My Progressive Web App',
      short_name: 'MyPWA',
      gcm_sender_id: '1088711235233' // <-- here
})
```

I tried this before, but I got the impression that it doesn't work.

**Comment by frlinw** [comment]
Do not use gcm_sender_id, it's legacy

> FCM / GCM and Chrome now support the standard Web Push Protocol, while sender authentication can be achieved by implementing VAPID, meaning your web app no longer needs a 'gcm_sender_id'.

ref: https://developers.google.com/web/updates/2016/07/web-push-interop-wins
