### ISSUE TITLE
Unable to include SVG icons

### ISSUE THREAD

**Issue by satazor** [arthurbergmz/webpack-pwa-manifest#47]
If there's a SVG icon inside `icons`, this package fails with the following error:

```
It was not possible to read 'src/icons/some.svg'.
```

This happens because we are using `jimp` to resize the images but it doesn't support SVGs. And it shouldn't because SVGs are scalable by nature, thus they don't need to be resampled. My suggestion is to detect SVGs via the `type` (and fallback to extension) and skip `jimp` if the detection identified a SVG.

Do you agree with this? If so, I will make a PR to implement this strategy.

**Comment by frlinw** [comment]
Indeed, jimp can process png, jpg and bmp so it would be nice to check if the file matchs one of these extensions (and maybe log a warning if you want to resize an unsupported image file extension like .webp)

**Comment by arthurbergmz** [comment]
@satazor sounds nice. if you make a PR, I will probably release it as **v3.4.2**.

**Comment by satazor** [comment]
@arthurbergmz 👍 will do.
