### ISSUE TITLE
How to use in template

### ISSUE THREAD

**Issue by HoneyryderChuck** [arthurbergmz/webpack-pwa-manifest#5]
I'm still missing how do I add this to my template. `HtmlWebpackPlugin` automatically handles chunks, but this is not a chunk, I guess.

**Comment by arthurbergmz** [comment]
This is a webpack plugin just like any other. Just add in the "plugins" array, on your webpack configuration, a new instance of WebpackPwaManinest, with your desired properties.

**Comment by HoneyryderChuck** [comment]
Not what I meant, I meant inserting the `<link ... />` tag in the index.html . 

I understand that this lib's purpose is only "bundling" the manifest.json and writing it to the output path, and adding the link is of no concern. Nevertheless, some guidelines on how to had the link tag could be useful in the README. 

I've just added it to my template, no plugins involved:

```
...
<link rel="manifest" href="/assets/manifest.json" />
...
```

Not having a dynamic way to setup the path will make it hard to invalidate caching or serving it from a CDN. Fingerprinting the manifest name could be this lib's concern, the rest can be done externally, I'm just not sure how.

**Comment by arthurbergmz** [comment]
Oh, I see. There's no options now, but I'm actually looking for a way of doing this for the next version. Thanks for your suggestion!

**Comment by HoneyryderChuck** [comment]
Sweet! thx 4 the feedback, will do my best to keep posted

**Comment by arthurbergmz** [comment]
✔ Added manifest fingerprinting and HTML injection (**html-webpack-plugin**).

**Comment by HoneyryderChuck** [comment]
I finally had time to integrate this. It works exactly as expected! Thx a bunch.
