### ISSUE TITLE
Disable fingerprints ignored in 3.5.0

### ISSUE THREAD

**Issue by BOOMER74** [arthurbergmz/webpack-pwa-manifest#51]
Option
```js
{
    fingerprints: false
}
```
stop working in 3.5.0. Manifest always created with fingerprints.

**Comment by arthurbergmz** [comment]
Not a priority now, since **v4.0.0** is coming out soon and **v3.5.0** will be very deprecated.

**Comment by WayneHiller** [comment]
How soon is soon?

**Comment by throrin19** [comment]
I have the same problem and this feature is realy important for me :/

**Comment by WayneHiller** [comment]
If you specify a filename it will not append the thumbprint. filename: "manifest.json"

**Comment by arthurbergmz** [comment]
Fixed in **v3.6.2**.
