### ISSUE TITLE
bad naming of manifest.json when fingerprints = false

### ISSUE THREAD

**Issue by ZiperRom1** [arthurbergmz/webpack-pwa-manifest#57]
When the option `fingerprints` is set to `false`, the output name of manifest is `manifest..json` instead of  `manifest.json` (double dot)

**Comment by seiryokusan** [comment]
Not sure if this helps but it was not occurring on 3.4.1. I've only seen this on 3.6.2 so far.

**Comment by christophermiles** [comment]
Happening for me on 3.6.2 too

**Comment by doug-wade** [comment]
Duplicate of #64
