### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by andreasonny83** [arthurbergmz/webpack-pwa-manifest#6]
Unfortunately, I'm getting a new error while Webpack is is compiling:

```
webpack: Compiling...
 95% emitting(node:26089) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: icon.sizes.pop is not a function
```

**Comment by arthurbergmz** [comment]
Can I see your webpack configuration, please? So I can simulate this error on my machine.

**Comment by andreasonny83** [comment]
sure thing. Have a look at the entire project: https://github.com/andreasonny83/online-board

**Comment by arthurbergmz** [comment]
Okay, I've cloned your repository and I'll execute some tests. I'm going to give a solution as soon as possible. Thank you!

**Comment by andreasonny83** [comment]
Thank you. The bug appears when I have the 'npm start' running in the background and webpack recompile the project while I'm working on some Typescript files. It should happen quite often.

**Comment by arthurbergmz** [comment]
Okay, it was a bug related to hot reload. It should be working now!
Thanks!

**Comment by andreasonny83** [comment]
Thanks again
