### ISSUE TITLE
Support for crossorigin attribute on injected link tag

### ISSUE THREAD

**Issue by kovcic** [arthurbergmz/webpack-pwa-manifest#60]
Hello,

I need support for `crossorigin="use-credentials"` on injected `<link>` tag.
Correct me if I'm wrong, but such option is not available.

Thx

**Comment by stonecold123** [comment]
Hope it gets merged soon!
https://github.com/arthurbergmz/webpack-pwa-manifest/pull/62

**Comment by doug-wade** [comment]
This was fixed in #62

**Comment by kovcic** [comment]
Works well, thank you!
