### ISSUE TITLE
Error: Unknown value of "background_color": rgb(...)

### ISSUE THREAD

**Issue by Spaxe** [arthurbergmz/webpack-pwa-manifest#61]
The Web Manifest Spec says the colour value can be of any valid CSS Level 3 syntax (https://w3c.github.io/manifest/#dom-webappmanifest-background_color). Using `rgb(..)` in the webpack plugin config results in error.

**Comment by wavebeem** [comment]
I think transparent needs to be supported too? It seems to be an option on https://www.pwabuilder.com/generate.
