### ISSUE TITLE
filename:'[name].[hash][ext]' generate 'name..json' when fingerprints:false

### ISSUE THREAD

**Issue by pfdgithub** [arthurbergmz/webpack-pwa-manifest#64]
```filename:'[name].[hash][ext]'``` generate ```'name..json'``` when ```fingerprints:false```
```filename:'[name].[hash][ext]'``` generate ```'name.hash.json'``` when ```fingerprints:true```

**Comment by doug-wade** [comment]
Fixed in #73 by @Diokuz (thanks!)
