### ISSUE TITLE
add Travis CI integration for continuous-integration testing

### ISSUE THREAD

**Issue by cvan** [arthurbergmz/webpack-pwa-manifest#67]
it'd be great to set this project to use the [Travis CI (via the free GitHub integration)](https://github.com/marketplace/travis-ci) service, which is free (for OSS projects).

the [tests](https://github.com/arthurbergmz/webpack-pwa-manifest/tree/master/tests) could then be run on pull requests (opened/modified), with reported test successes and failures (via the built-in hooks in the GitHub integration).

let me know if you want help with this. (related: for issue #63, I did some troubleshooting with the tests, but I'm still stuck on why the test files cannot be found on my system.)

**Comment by doug-wade** [comment]
Thanks for the suggestion; I intend to do this.  I'm working with the repo owner to get the correct permissions.
