### ISSUE TITLE
Is there any support for iOS splash-screens?

### ISSUE THREAD

**Issue by ghashi** [arthurbergmz/webpack-pwa-manifest#68]
Is there any support for iOS splash-screens (with Auto image resizing, image fingerprinting, auto injection on HTML)?

The feature I'm talking about is this: https://appsco.pe/developer/splash-screens

**Comment by doug-wade** [comment]
The platform-independent way to generate a splash screen is using the the name property, the background_color property and the icons array in manifest.json (see, for instance [this Medium piece](https://medium.com/@applification/progressive-web-app-splash-screens-80340b45d210) ).  This is the way for specifying splash screens that we intend to support.
