### ISSUE TITLE
[Disclaimer] Inactivity

### ISSUE THREAD

**Issue by arthurbergmz** [arthurbergmz/webpack-pwa-manifest#70]
Hello!

I owe you apologizes. 2018 has been such a great year and I've been busy all year long, working on a lot of projects. Because of that, this project has become inactive. It's true there is a branch for a new version, but I would like to work on a lot of stuff and I just can't do it right now. Feel free if you want to create a fork of this project and keep up with it, since, for the moment, I just can't keep working on this.

Best regards,
Arthur A. Bergamaschi.

**Comment by doug-wade** [comment]
Hi @arthurbergmz!  Would you be willing to allow development to continue in this repository and with this npm module name?  I'd be willing to watch the repo and keep up with PRs and issues -- to maintain the project.

**Comment by arthurbergmz** [comment]
@doug-wade I would be glad to make you a collaborator!
I'll be coming back to the open-source world very soon, I'm just really busy since a couple of months ago because of college and this new job in Montréal. I'm still trying to keep up with side-projects, but it has been kinda hard.

I'll add you as a collaborator. I would also be happy if you continue the "next" branch, if possible! The idea is just recoding it to have a faster and clear code.

Thank you for your support!

**Comment by csantiago132** [comment]
@arthurbergmz im willing to help as well! Im new to dev but I can do the small stuff/anything you guys want while I learn more

**Comment by doug-wade** [comment]
Hi @csantiago132!  My biggest concern is #56 and #32, which I think are duplicates.  It'd be really helpful to have a minimal repro (like in a repository somewhere) or a failing unit test as a PR, if you're looking for somewhere to start.  The same can be said for #32 -- it'd be easier if we had a repro or failing unit test.  If you're looking for somewhere to start, that might be a good place.

Personally, I plan on picking up #61 next and then doing a release to pick up the crossorigin stuff I just merged into a 3.7.0 release.

**Comment by csantiago132** [comment]
@doug-wade ok will do my best. ill create one on my end and have a repo

**Comment by thasmo** [comment]
I'd love to see #56 and #66 and #32 being worked on. I'm not familiar with how webpack plugins work, but I'd imagine it's possible to somehow emit new files to webpack, and webpack passes them to the appropriate loaders etc. so these files will be handled like any other asset/dependency.

**Comment by arthurbergmz** [comment]
Hello, everyone!

Branch `next` just got update after a while. I'm working again on this project ;)

**Comment by arthurbergmz** [comment]
By the way, thanks everyone who contributed in the meanwhile! You guys nailed it.
