### ISSUE TITLE
what is icon fingerprinting?

### ISSUE THREAD

**Issue by vesper8** [arthurbergmz/webpack-pwa-manifest#98]
this is the first time I hear of this and googling it did not bring up anything relevant... is that just another term for cache-busting through the use of hashes in the filename? or does it mean more than that?

**Comment by marklai1998** [comment]
should be the hashes of the icon
fingerprint means add the file hash to the file name like a<hash>.png
it is common to use it to refresh the cache of CDN

**Comment by vesper8** [comment]
thanks for clarifying
